services:
  ai-portfolio:
    image: ghcr.io/skyvence/ai-portfolio:latest
    networks:
      - proxy-net
    labels:
      - "shepherd.enable=true"
      - "shepherd.auth.config=default"

networks:
  proxy-net:
    external: true
